### ISSUE TITLE
UnitOfMeasurement : LBS is hard coded in the XML

### ISSUE THREAD

**Issue by sitehopper** [beaudierman/ups#6]
File UPS.php, line 178:
\<Code>LBS\</Code>
This should be 
\<Code>' . $measurement . '\</Code>

other then that, great package! Thanks

**Comment by InstanceOfMichael** [comment]
Are you sure you are not using an older version?

https://github.com/beaudierman/ups/blob/master/src/Beaudierman/Ups/Ups.php#L178

https://github.com/beaudierman/ups/issues/1

**Comment by sitehopper** [comment]
Im pulling it in with the instructions on https://packagist.org/packages/beaudierman/ups
So in my composer I have this:
"beaudierman/ups": "1.*"

Should I do this differently?

**Comment by beaudierman** [comment]
@sitehopper This has been fixed in the latest v1.1.1 release.

**Comment by carcinocron** [comment]
@sitehopper maybe try ``composer update beaudierman/ups"

**Comment by rbijkercom** [comment]
It works! I did another update and I see that composer installed beaudierman/ups (v1.1.1). 
Everything is working well :-). Great package! Thanks!
